---
NumViews: 1
ViewNames: # Optional

NumLabelPoints: 4 # The number of physical/3D points
LabelPointNames: # Optional

LabelMode: TEMPLATE # See LabelMode.m

Trx:
  ZoomRadius: 100
  ZoomRadiusTight: 10
  ZoomFactorDefault: 0.4 # Should be named 'ZoomRadiusDefault'
  TrajColor: [1,1,0]
  TrajLineStyle: '-'
  TrajLineWidth: 1
  TrajColorCurrent: [1,0,0]
  TrxMarker: 'x'
  TrxMarkerSize: 10
  TrxLineWidth: 3
  ShowTrx: 1
  ShowTrxCurrentTargetOnly: 0

View: 
  XDir: 'n'
  YDir: 'r'
  CLim:
    Min:
    Max:
  Gamma: 
  FigurePos:
    left: 
    bottom: 
    width: 
    height: 
  AxisLim:
    xmin: 
    xmax: 
    ymin:  
    ymax: 
  InvertMovie:
  AxColor: [1,1,1]
  AxFontSize: 12
  ShowAxTicks: 0
  ShowGrid: 0
  CenterOnTarget: 0
  RotateTargetUp: 0

Movie:
  ForceGrayScale: 1
  FrameStepBig: 10
  PlaySegmentRadius: 50

LabelPointsPlot:
  ColorMapName: 'spring'
  Marker: '+'
  MarkerSize: 6
  LineWidth: 2
  FontSize: 14
  OccludedMarker: 'o'
  
  TemplateMode:
    TemplatePointColor: [1,1,1]
    SelectedPointMarker: 'x'
    SelectedOccludedMarker: 's'

  SequenceMode:

  HighThroughputMode:
    NFrameSkip: 5
    UnlabeledPointColor: [1,1,1]
    OtherLabeledPointColor: [0,1,0]

  ErrorCorrectMode:
    SelectedPointMarker: 'x'
    SelectedOccludedMarker: 's'
    MarkedMarkerSize: 16

  MultiViewCalibratedMode:
    EpipolarLineWidth: 2
    ReconstructedMarker: 'o'
    ReconstructedMarkerSize: 6
    ReconstructedLineWidth: 2

InfoTimelines:
  FrameRadius: 50 # default timeline radius (in frames)
  XColor: [0.8,0.8,0.8] # ax.XColor
  dXTick: 10 

Track:
  Enable: 0
  Type: CPRLabelTracker
  PredictFrameStep: 5
  PredictFrameStepBig: 10
  PredictNeighborhood: 100
  PredictPointsPlot: # Plot cosmetics for tracking results
    Marker: '+'
    MarkerSize: 10
    LineWidth: 2
  PredictInterpolate: 0         # If true, tracked results are interpolated/extrapolated to all frames when visualizing
  PredictInterpolatePointsPlot: # Plot cosmetics for interpolated tracking results
    Marker: '.'
    MarkerSize: 5
    LineWidth: 1

CPRLabelTracker:
  StoreFullTracking: 0 # If true, store tracking results with replicates/iterations
  PredictReplicatesPlot: # Plot cosmetics for tracking replicates
    Marker: '.'
    MarkerSize: 15

Shortcuts: # shortcuts. case insensitive!
  menu_file_load: o # file -> load project
  menu_file_new: n # file -> new project
  menu_file_save: s # file -> save project
  menu_file_managemovies: m # file -> manage movies
  menu_file_quit: q # file -> quit
  menu_view_hide_labels: h # view -> hide labels
  menu_view_hide_predictions: p # view -> hide predictions
  menu_view_hide_trajectories: j # view -> hide trajectories
  menu_track_retrain: r # track -> retrain
  menu_track_set_labels: l # track -> set manual labels to predicted pose
  tbAccept: x # accept toggle button
  pbTrain: t # train pushbutton
  pbTrack: k # track pushbutton

...
